# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bA8uyGK0-DqXyiwxaHlW0DxMFBvPm1XX
"""

pip install psutil

import psutil

cpu_percent = psutil.cpu_percent()
print("CPU usage: {}%".format(cpu_percent))

mem = psutil.virtual_memory()
mem_total = mem.total
mem_used = mem.used
mem_percent = mem.percent

print("Total memory: {} bytes".format(mem_total))
print("Used memory: {} bytes".format(mem_used))
print("Memory usage: {}%".format(mem_percent))

disk = psutil.disk_usage('/')
disk_total = disk.total
disk_used = disk.used
disk_percent = disk.percent

print("Total disk space: {} bytes".format(disk_total))
print("Used disk space: {} bytes".format(disk_used))
print("Disk usage: {}%".format(disk_percent))

import psutil

# Get CPU usage percentage
cpu_percent = psutil.cpu_percent()

# Get RAM usage information
mem = psutil.virtual_memory()
mem_total = mem.total
mem_used = mem.used
mem_percent = mem.percent

# Get hard disk usage information
disk = psutil.disk_usage('/')
disk_total = disk.total
disk_used = disk.used
disk_percent = disk.percent

# Create dictionary to store system resource data
system_resources = {
    "cpu": {
        "usage_percent": cpu_percent
    },
    "memory": {
        "total": mem_total,
        "used": mem_used,
        "usage_percent": mem_percent
    },
    "disk": {
        "total": disk_total,
        "used": disk_used,
        "usage_percent": disk_percent
    }
}

# Print the dictionary
print(system_resources)

